### ISSUE TITLE
Compilation errors; kmod on Mint20 and Rocky9

### ISSUE THREAD

**Issue by c-r-h** [versity/scoutfs#173]
### Linux Mint 20.3 (Ubuntu 20.04 "Focal Fossa")
Following the most basic download & build steps:
- `git clone https://github.com/versity/scoutfs.git`
- `cd scoutfs/kmod ; make`
```
/bin/sh: 1: sparse: not found
make SCOUTFS_GIT_DESCRIBE=heads/main-0-g965b69 RPM_GITHASH=965b692 CONFIG_SCOUTFS_FS=m -C /lib/modules/5.4.0-177-generic/build M=/<path>/scoutfs/kmod/src EXTRA_CFLAGS="-Werror"
make[1]: Entering directory '/usr/src/linux-headers-5.4.0-177-generic'
  AR      /<path>/scoutfs/kmod/src/built-in.a
  :
  :
  CC [M]  /<path>/scoutfs/kmod/src/net.o
/<path>/scoutfs/kmod/src/net.c: In function ‘sock_opts_and_names’:
/<path>/scoutfs/kmod/src/net.c:914:44: error: ‘SO_SNDTIMEO’ undeclared (first use in this function); did you mean ‘SO_TXTIME’?
  914 |  ret = kernel_setsockopt(sock, SOL_SOCKET, SO_SNDTIMEO,
      |                                            ^~~~~~~~~~~
      |                                            SO_TXTIME
/<path>/scoutfs/kmod/src/net.c:914:44: note: each undeclared identifier is reported only once for each function it appears in
/<path>/scoutfs/kmod/src/net.c: In function ‘scoutfs_net_connect_worker’:
/<path>/scoutfs/kmod/src/net.c:1066:44: error: ‘SO_SNDTIMEO’ undeclared (first use in this function); did you mean ‘SO_TXTIME’?
 1066 |  ret = kernel_setsockopt(sock, SOL_SOCKET, SO_SNDTIMEO,
      |                                            ^~~~~~~~~~~
      |                                            SO_TXTIME
make[2]: *** [scripts/Makefile.build:270: /<path>/scoutfs/kmod/src/net.o] Error 1
make[1]: *** [Makefile:1778: /<path>/scoutfs/kmod/src] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.4.0-177-generic'
make: *** [Makefile:39: module] Error 2`
```
The above errors can be resolved by changing `SO_SNDTIMEO` to `SO_SNDTIMEO_OLD` in `net.c`.  The same must be done for `SO_RCVTIMEO` in `quorum.c`.  I _**do not**_ know if that is a correct solution.

Once those changes have been made:
```
/<path>/scoutfs/kmod/src/quorum.c: In function ‘set_quorum_block_event’:
/<path>/scoutfs/kmod/src/quorum.c:489:2: error: implicit declaration of function ‘getnstimeofday64’; did you mean ‘getnstimeofday’? [-Werror=implicit-function-declaration]
  489 |  getnstimeofday64(&ts);
      |  ^~~~~~~~~~~~~~~~
      |  getnstimeofday
/<path>/scoutfs/kmod/src/quorum.c: In function ‘scoutfs_quorum_fence_leaders’:
/<path>/scoutfs/kmod/src/quorum.c:636:1: error: the frame size of 1552 bytes is larger than 1024 bytes [-Werror=frame-larger-than=]
  636 | }
      | ^
cc1: all warnings being treated as errors
make[2]: *** [scripts/Makefile.build:270: /<path>/scoutfs/kmod/src/quorum.o] Error 1
make[1]: *** [Makefile:1778: /<path>/scoutfs/kmod/src] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.4.0-177-generic'
make: *** [Makefile:39: module] Error 2
```

It appears to me that all of the above errors are due to changes made to accommodate 64-bit time in the kernel.  The `SO_xxxTIMEO_OLD` and `SO_xxxTIMEO_NEW` designations appear to have been transitional designations.  [One note that I found](https://github.com/ccp-project/ccp-kernel/issues/22) when researching these errors states that `getnstimeofday()` has been deprecated and is no longer available; `ktime_get_real_ts64()` should be used instead.

#### Mint Summary
It appears that time-related code in ScoutFS is out of step with current kernel releases.  There is also a network frame size error reported in function `quorum.c:scoutfs_quorum_fence_leaders()` (see above).

### Rocky 9
Attempts to compile this module on Rocky9 fail rather more dramatically than they do on Mint.  The first error encountered:
```
$ make
/bin/sh: line 1: sparse: command not found
make SCOUTFS_GIT_DESCRIBE=heads/main-0-g965b69 RPM_GITHASH=965b692 CONFIG_SCOUTFS_FS=m -C /lib/modules/5.14.0-284.30.1.el9_2.x86_64/build M=/<path>/scoutfs/kmod/src EXTRA_CFLAGS="-Werror"
make[1]: Entering directory '/usr/src/kernels/5.14.0-284.30.1.el9_2.x86_64'
  CC [M]  /<path>/scoutfs/kmod/src/acl.o
In file included from /<path>/scoutfs/kmod/src/acl.c:22:
/<path>/scoutfs/kmod/src/scoutfs_trace.h:27:10: fatal error: linux/unaligned/access_ok.h: No such file or directory
   27 | #include <linux/unaligned/access_ok.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [scripts/Makefile.build:321: /<path>/scoutfs/kmod/src/acl.o] Error 1
make[1]: *** [Makefile:1923: /<path>/scoutfs/kmod/src] Error 2
make[1]: Leaving directory '/usr/src/kernels/5.14.0-284.30.1.el9_2.x86_64'
make: *** [Makefile:39: module] Error 2
```
Rocky9 (and, I assume, the RHEL it's based upon) does not provide `/usr/src/linux-headers-<kvers>/include/linux/unaligned/access_ok.h`.  Rocky provides `/usr/src/kernels/<kversion>/include/asm-generic/unaligned.h`, which provides the same set of functions.  

Changing the include file in `scoutfs_trace.h` does resolve above error...but generates a whole new set of errors indicating further incompatibilities with the Rocky/RHEL ecosphere.

#### Rocky Summary
It appears that ScoutFS isn't generally built on Rocky/RHEL.  I am sure that there are standard ways to provide cross-ecosphere compilability, but I don't know what those are offhand.  My goal is to run ScoutFS on a Rocky9 system, so I'd like to ensure that it can be compiled on Rocky/RHEL.

---
_**Note:**  I replaced the actual path with `<path>` in the text above, and used colons (":") on their own lines to indicate that I had snipped out some output._

**Comment by c-r-h** [comment]
May be related to PR  #151.

**Comment by benmcclelland** [comment]
> May be related to PR #151.

Yes, work is still in progress for el9 support in that branch. We are expecting this to be completed fairly soon.  There is another change outstanding to add quota support first, then the plan is to rebase that el9 PR and get it merged.

There are currently no plans for supporting mint/ubuntu kernel versions from our internal team, but we might be able to give guidance if someone else wanted to work on this.

**Comment by c-r-h** [comment]
> There are currently no plans for supporting mint/ubuntu kernel versions from our internal team, but we might be able to give guidance if someone else wanted to work on this.

Huh...  It seemed (based on what I encountered in the main branch) as though the code was much more closely aligned with Ubuntu/Mint than EL.  I don't personally need mint/ubuntu support, but it doesn't look as though it would be too much of a stretch.

I'll watch this issue and PR#151 for updates.

**Comment by aversecat** [comment]
> I'll watch this issue and PR#151 for updates.

If you compile from that branch and encounter any issues on `el9`, please report them back to me!

**Comment by c-r-h** [comment]
> If you compile from that branch and encounter any issues on `el9`, please report them back to me!
Quick note that I needed to do two things to get the module to compile:
- I installed the `dwarves` package for `pahole`.  This is probably standard operating procedure for folks who spend more time in the kernel than I typically do.
- I had to make a link to `vmlinux`: `ln -s //sys/kernel/btf/vmlinux /usr/lib/modules/`uname -r`/build/`
Those two steps were required in order to get the
```
  BTF [M] /home/crh/work/code/scoutfs/kmod/src/scoutfs.ko
```
step to complete without error.

I have now built the module and will start testing it.  Thanks for your help!

**Comment by c-r-h** [comment]
I'm almost there...
- In order to compile the `scoutfs` utility, I needed to install `libblkid-devel` and `libuuid-devel`.  No biggie...
- Since I'm only doing testing, I figured I would use files instead of block devices.  I created a 128GB metadata file and a 256GB data file: `/data/scoutfs.meta` and `/data/scoutfs.data`.
- I created `loop` devices, so that ScoutFS would think the files were block devices.
```
# losetup /dev/loop0 /data/scoutfs.meta
# losetup /dev/loop1 /data/scoutfs.data
```
- Then I created the filesystem:
```
# ./src/scoutfs mkfs --force -Q 0,127.0.0.1,12348 /dev/loop0 /dev/loop1
Created scoutfs filesystem:
  meta device path:       /dev/loop0
  data device path:       /dev/loop1
  fsid:                   a0e6bf74551765cd
  uuid:                   810272b3-58ce-4b7e-a578-ed0198bc3009
  format version:         1
  64KB metadata blocks:   2097152 (128.00 GB)
  4KB data blocks:        67108864 (256.00 GB)
  quorum config version:  1
  quorum slots:           0: 127.0.0.1:12348
```
...and now I'm stuck trying to mount the filesystem.  The [documentation](https://github.com/versity/scoutfs-kmod-dev) that I was able to find appears to be outdated.  I get this from `dmesg`:
```[1155008.763253] scoutfs f.000000.r.a583b4 error: Unknown or malformed option, "server_addr=127.0.0.1"```
when using the format provided in the older documentation.

I tried leaving out the `server_addr` option:
```mount -t scoutfs -o metadev_path=/dev/loop0 /dev/loop1 /mnt```
...and the command got stuck, probably hanging on a system call.  `kill`ing the process didn't help.  I had to reboot the system.

Soooooo close!  What would the proper mount command be?

**Comment by aversecat** [comment]
To do a simple one-node no failover mount you can do something like this:

```
scoutfs mkfs -A -f -Q 0,127.0.0.1,53000 <device 1> <device 2>
mount -t scoutfs -o metadev_path=<device 1>,quorum_slot_nr=0 <device 2> <mount point>
```

**Comment by aversecat** [comment]
Closing this issue as we're not supporting `mint` or `el9` right now. Please file separate issues for usage problems etc., it helps to keep our issue tracker a bit better organized.
